Blog.UI/Models/PopularAndRecentPostResponseModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Blog.Entity;

namespace Blog.UI.Models
{
    public class PopularAndRecentPostResponseModel
    {
        public List<CategoryDetail> PopularPost { get; set; } = new List<CategoryDetail>();
        public List<CategoryDetail> RecentPost { get; set; } = new List<CategoryDetail>();

    }
}

Blog.UI/Controllers/CategoryController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.UI.Controllers
{
    public class CategoryController : ControllerBase
    {
        // GET: Category
        public ActionResult Index()
        {
            return View();
        }
    }
}

Blog.UI/Controllers/CategoryDetailController.cs
using Blog.Model.ResponseModel;
using Blog.UI.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.UI.Controllers
{
    public class CategoryDetailController : ControllerBase
    {
        // GET: CategoryDetail
        public PartialViewResult PopularAndRecentPartial()
        {

            PopularAndRecentPostResponseModel response = new PopularAndRecentPostResponseModel();
            response.PopularPost = DataService.CategoryDetailManager.GetPopularPost();
            response.RecentPost = DataService.CategoryDetailManager.GetRecentPost();
            return PartialView(response);
            //return PartialView("PopularAndRecentPartial", response);
        }



        public PartialViewResult GetAllPost(int pageId=1)
        {
            IPagedList<CategoryDetailResponseModel> response = DataService.CategoryDetailManager.GetAllPost().ToPagedList(pageId,3);
            return PartialView("HomePageBlogPostPartial", response);
        }

        public ActionResult PostByCategory(int ?id, int page = 1)
        {
            IPagedList<CategoryDetailResponseModel> response = DataService.CategoryDetailManager.GetAllPostByCategoriId(id.Value).ToPagedList(page, BlogPostCountForEveryPage);
            return View(response);
        }


        public ActionResult PostByTag(int? id, int page = 1)
        {
            IPagedList<CategoryDetailResponseModel> response = DataService.CategoryDetailManager.GetAllPostByTagId(id.Value).ToPagedList(page, BlogPostCountForEveryPage);
            return View(response);
        }


        public ActionResult PostBySearchKey(string key,int page=1)
        {
            IPagedList<CategoryDetailResponseModel> response = DataService.CategoryDetailManager.PostBySearchKey(key).ToPagedList(page, BlogPostCountForEveryPage);
            return View(response);
            //var response = DataService.CategoryDetailManager.PostBySearchKey(key);
            //return View(response);
        }

    }
}

Blog.UI/Controllers/HomeController.cs
using Blog.Model.ResponseModel;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.UI.Controllers
{

    //Controllerda bulunan action adlarını İlgili klasörde arara bulamaz ise Shared klasöründe arar
    public class HomeController : ControllerBase
    {
     
        //Ana sayfa içerindeki postları sayfalayarak getirir 
        public ActionResult Index(int page = 1)
        {
            IPagedList<CategoryDetailResponseModel> response = DataService.CategoryDetailManager.GetAllPost().ToPagedList(page, BlogPostCountForEveryPage);
            return View(response);
        }

        public PartialViewResult HeadPartial()
        {
            var catList = DataService.CategoryManager.CategoriList();
            return PartialView(catList);//MVC de KOntrollerdan view'e veri gönderme Yöntemi View içerisine direk veri gömülür ve View tarafında veri alınır
        }

        public PartialViewResult RightCategoryPartial()
        {
            var catList = DataService.CategoryManager.CategoriList();
            return PartialView(catList);//MVC de KOntrollerdan view'e veri gönderme Yöntemi View içerisine direk veri gömülür ve View tarafında veri alınır
        }


        public PartialViewResult RecentFlickrImages()
        {
            var images = DataService.BlogHomePageManager.BlogHomePageImages();
            return PartialView("RecentFlickrImagesPartial", images);
        }

    }
}

Blog.UI/Controllers/PageSectionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.UI.Controllers
{
    public class PageSectionController : ControllerBase
    {
        // GET: PageSection
        public PartialViewResult GetRightWidget()
        {
            var content = DataService.PageSectionManager.GetPageSectionContentBySectionName("Blog Ana Sayfası");
            return PartialView("RightWidgetText", content);
        }
    }
}

Blog.UI/Controllers/SliderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.UI.Controllers
{
    public class SliderController : ControllerBase
    {
        // GET: Slider
        public ActionResult Index()
        {
            return View();
        }
    }
}

Blog.UI/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.UI.Controllers
{
    public class TagController : ControllerBase
    {
        // GET: GetAllTags
        public PartialViewResult GetAllTags()
        {
            var tagList = DataService.TagManager.TagList();
            return PartialView("TagPartial", tagList);
        }
    }
}

Blog.UI/Views/CategoryDetail/PostByCategory.cshtml
@using Blog.Model.ResponseModel
@using PagedList
@using PagedList.Mvc
@model IPagedList<CategoryDetailResponseModel>
@{
                /**/

                ViewBag.Title = "PostByCategory";
}

<!-- Blog Post -->
@foreach (var item in Model)
{
    <article class="post">
        <div class="row">
            <!-- Image  post -->
            <div class="col-md-5">
                <!-- Image Post  -->
                <div class="post-image">
                    <!-- Simple-slide -->
                    <div id="carousel-example-generic" class="carousel slide bs-docs-carousel-example">
                        <ol class="carousel-indicators">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1" class="">
                            <li data-target="#carousel-example-generic" data-slide-to="2" class=""></li>
                        </ol>
                        <div class="carousel-inner">
                            <div class="item active">
                                <img src="~/Content/UI/img/works/1.jpg" alt="">
                            </div>
                            <div class="item">
                                <img src="~/Content/UI/img/works/2.jpg" alt="">
                            </div>
                            <div class="item">
                                <img src="~/Content/UI/img/works/3.jpg" alt="">
                            </div>
                        </div>
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="icon-prev"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="icon-next"></span>
                        </a>
                    </div>
                    <!-- End Simple-slide -->
                </div>
                <!-- End Image Post  -->
            </div>
            <!-- End Image  post -->
            <!-- Info post -->
            <div class="col-md-7">
                <h3>
                    <a href="blog-post.html">
                        @Blog.Helper.StringHelper.ShortenedStringWordsAndThreeDot(@item.Header, 35)
                    </a>
                </h3>
                <!-- Post Meta -->
                <div class="row">
                    <div class="col-md-12">
                        <div class="post-meta">
                            <span><i class="fa fa-calendar"></i> Nov 10, 2012 </span>
                            <span><i class="fa fa-user"></i> By <a href="#">Admin</a> </span>
                            <span><i class="fa fa-tag"></i> <a href="#">Duis</a>, <a href="#">News</a></span>
                            <span><i class="fa fa-comments"></i> <a href="#">(12)</a></span>
                        </div>
                    </div>
                </div>
                <!-- End Post Meta -->
                <p>

                    @Blog.Helper.StringHelper.ShortenedStringWordsAndThreeDot(@item.Content, 210)
                </p>
                <a href="blog-post.html" class="btn btn-primary">Read more...</a>
            </div>
            <!--End Info post -->
        </div>
    </article>

}

@if (Model.Count >= Blog.UI.Controllers.ControllerBase.BlogPostCountForEveryPage &&  Model.PageCount > 1
    ||  Model.PageCount > 1
    )
{
    <!-- Pagination -->
    <ul class="pagination">
        @Html.PagedListPager(Model, page => Url.Action("/PostByCategory/", new { id = Model[0].CategoryId, page }))
    </ul>
    <!-- End Pagination -->
}

@*@Html.PagedListPager(Model, page => Url.Action("Products",
    new { page, sortOrder = ViewBag.CurrentSort,  Category = ViewBag.Category, Brand = ViewBag.Brand }))*@

Blog.UI/Views/CategoryDetail/PostBySearchKey.cshtml
@using Blog.Model.ResponseModel
@using PagedList
@using PagedList.Mvc
@model IPagedList<CategoryDetailResponseModel>

@{
    ViewBag.Title = "PostBySearchKey";
}

@if (Model != null && Model.TotalItemCount > 0)
{
    <h4>Toplam Bulunan Makale Sayısı :@Model.TotalItemCount</h4>
}
else
{
    <h4>Aradığınız kelimeyle eşleşen makale bulunmadı</h4>
}


<!-- Blog Post -->
@foreach (var item in Model)
{
    <article class="post">
        <div class="row">
            <!-- Image  post -->
            <div class="col-md-5">
                <!-- Image Post  -->
                <div class="post-image">
                    <!-- Simple-slide -->
                    <div id="carousel-example-generic" class="carousel slide bs-docs-carousel-example">
                        <ol class="carousel-indicators">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1" class="">
                            <li data-target="#carousel-example-generic" data-slide-to="2" class=""></li>
                        </ol>
                        <div class="carousel-inner">
                            <div class="item active">
                                <img src="~/Content/UI/img/works/1.jpg" alt="">
                            </div>
                            <div class="item">
                                <img src="~/Content/UI/img/works/2.jpg" alt="">
                            </div>
                            <div class="item">
                                <img src="~/Content/UI/img/works/3.jpg" alt="">
                            </div>
                        </div>
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="icon-prev"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="icon-next"></span>
                        </a>
                    </div>
                    <!-- End Simple-slide -->
                </div>
                <!-- End Image Post  -->
            </div>
            <!-- End Image  post -->
            <!-- Info post -->
            <div class="col-md-7">
                <h3>
                    <a href="blog-post.html">
                        @Blog.Helper.StringHelper.ShortenedStringWordsAndThreeDot(@item.Header, 35)
                    </a>
                </h3>
                <!-- Post Meta -->
                <div class="row">
                    <div class="col-md-12">
                        <div class="post-meta">
                            <span><i class="fa fa-calendar"></i> Nov 10, 2012 </span>
                            <span><i class="fa fa-user"></i> By <a href="#">Admin</a> </span>
                            <span><i class="fa fa-tag"></i> <a href="#">Duis</a>, <a href="#">News</a></span>
                            <span><i class="fa fa-comments"></i> <a href="#">(12)</a></span>
                        </div>
                    </div>
                </div>
                <!-- End Post Meta -->
                <p>

                    @Blog.Helper.StringHelper.ShortenedStringWordsAndThreeDot(@item.Content, 210)
                </p>
                <a href="blog-post.html" class="btn btn-primary">Read more...</a>
            </div>
            <!--End Info post -->
        </div>
    </article>

}

@if (Model.Count >= Blog.UI.Controllers.ControllerBase.BlogPostCountForEveryPage && Model.PageCount > 1
    || Model.PageCount > 1
    )
{
    <!-- Pagination -->
    <ul class="pagination">
        @Html.PagedListPager(Model, page => Url.Action("/PostByCategory/", new { id = Model[0].CategoryId, page }))
    </ul>
    <!-- End Pagination -->
}

Blog.UI/Views/CategoryDetail/PostByTag.cshtml
@{
    ViewBag.Title = "PostByTag";
}


@using Blog.Model.ResponseModel
@using PagedList
@using PagedList.Mvc
@model IPagedList<CategoryDetailResponseModel>
@{
    /**/

    ViewBag.Title = "PostByCategory";
}

<!-- Blog Post -->
@foreach (var item in Model)
{
    <article class="post">
        <div class="row">
            <!-- Image  post -->
            <div class="col-md-5">
                <!-- Image Post  -->
                <div class="post-image">
                    <!-- Simple-slide -->
                    <div id="carousel-example-generic" class="carousel slide bs-docs-carousel-example">
                        <ol class="carousel-indicators">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1" class="">
                            <li data-target="#carousel-example-generic" data-slide-to="2" class=""></li>
                        </ol>
                        <div class="carousel-inner">
                            <div class="item active">
                                <img src="~/Content/UI/img/works/1.jpg" alt="">
                            </div>
                            <div class="item">
                                <img src="~/Content/UI/img/works/2.jpg" alt="">
                            </div>
                            <div class="item">
                                <img src="~/Content/UI/img/works/3.jpg" alt="">
                            </div>
                        </div>
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="icon-prev"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="icon-next"></span>
                        </a>
                    </div>
                    <!-- End Simple-slide -->
                </div>
                <!-- End Image Post  -->
            </div>
            <!-- End Image  post -->
            <!-- Info post -->
            <div class="col-md-7">
                <h3>
                    <a href="blog-post.html">
                        @Blog.Helper.StringHelper.ShortenedStringWordsAndThreeDot(@item.Header, 35)
                    </a>
                </h3>
                <!-- Post Meta -->
                <div class="row">
                    <div class="col-md-12">
                        <div class="post-meta">
                            <span><i class="fa fa-calendar"></i> Nov 10, 2012 </span>
                            <span><i class="fa fa-user"></i> By <a href="#">Admin</a> </span>
                            <span><i class="fa fa-tag"></i> <a href="#">Duis</a>, <a href="#">News</a></span>
                            <span><i class="fa fa-comments"></i> <a href="#">(12)</a></span>
                        </div>
                    </div>
                </div>
                <!-- End Post Meta -->
                <p>

                    @Blog.Helper.StringHelper.ShortenedStringWordsAndThreeDot(@item.Content, 210)
                </p>
                <a href="blog-post.html" class="btn btn-primary">Read more...</a>
            </div>
            <!--End Info post -->
        </div>
    </article>

}

@*Controller'a Uı tarafından erişip işlem yapabiliriz*@ 
@if (Model.Count >= Blog.UI.Controllers.ControllerBase.BlogPostCountForEveryPage && Model.PageCount > 1
    || Model.PageCount > 1
    )
{
    <!-- Pagination -->
    <ul class="pagination">
        @Html.PagedListPager(Model, page => Url.Action("/PostByTag/", new { id = Model[0].TagId, page }))
    </ul>
    <!-- End Pagination -->
}

@*@Html.PagedListPager(Model, page => Url.Action("Products",
    new { page, sortOrder = ViewBag.CurrentSort,  Category = ViewBag.Category, Brand = ViewBag.Brand }))*@

Blog.UI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}



@*<!-- Blog Post -->
@Html.Action("GetAllPost", "CategoryDetail")
<!-- End Blog Post -->*@


@using Blog.Model.ResponseModel
@using PagedList
@using PagedList.Mvc
@model IPagedList<CategoryDetailResponseModel>
<!-- Blog Post -->

    @foreach (var item in Model)
    {
        <article class="post">
            <div class="row">
                <!-- Image  post -->
                <div class="col-md-5">
                    <!-- Image Post  -->
                    <div class="post-image">
                        <!-- Simple-slide -->
                        <div id="carousel-example-generic" class="carousel slide bs-docs-carousel-example">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="1" class="">
                                <li data-target="#carousel-example-generic" data-slide-to="2" class=""></li>
                            </ol>
                            <div class="carousel-inner">
                                <div class="item active">
                                    <img src="~/Content/UI/img/works/1.jpg" alt="">
                                </div>
                                <div class="item">
                                    <img src="~/Content/UI/img/works/2.jpg" alt="">
                                </div>
                                <div class="item">
                                    <img src="~/Content/UI/img/works/3.jpg" alt="">
                                </div>
                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                <span class="icon-prev"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                <span class="icon-next"></span>
                            </a>
                        </div>
                        <!-- End Simple-slide -->
                    </div>
                    <!-- End Image Post  -->
                </div>
                <!-- End Image  post -->
                <!-- Info post -->
                <div class="col-md-7">
                    <h3><a href="blog-post.html">           
                        @Blog.Helper.StringHelper.ShortenedStringWordsAndThreeDot(@item.Header, 35)</a></h3>
                    <!-- Post Meta -->
                    <div class="row">
                        <div class="col-md-12">
                            <div class="post-meta">
                                <span><i class="fa fa-calendar"></i> Nov 10, 2012 </span>
                                <span><i class="fa fa-user"></i> By <a href="#">Admin</a> </span>
                                <span><i class="fa fa-tag"></i> <a href="#">Duis</a>, <a href="#">News</a></span>
                                <span><i class="fa fa-comments"></i> <a href="#">(12)</a></span>
                            </div>
                        </div>
                    </div>
                    <!-- End Post Meta -->
                    <p>

                        @Blog.Helper.StringHelper.ShortenedStringWordsAndThreeDot(@item.Content, 210)
                    </p>
                    <a href="blog-post.html" class="btn btn-primary">Read more...</a>
                </div>
                <!--End Info post -->
            </div>
        </article>

    }

    <!-- Pagination -->
    <ul class="pagination">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))

    </ul>
    <!-- End Pagination -->

<!-- End Blog Post -->

Blog.UI/Views/Shared/FooterBottom.cshtml
<footer class="footer-bottom">
    <div class="container">
        <div class="row">

            <!-- Nav-->
            <div class="col-md-8">
                <div class="logo-footer">
                    <h2><span>R</span>oker<span>.</span></h2>
                </div>
                <!-- Menu-->
                <ul class="menu-footer">
                    <li><a href="index.html">HOME</a> </li>
                    <li><a href="about-us.html">ABOUT</a></li>
                    <li><a href="services.html">SERVICES</a></li>
                    <li><a href="work-3-columns.html">PORTFOLIO</a></li>
                    <li><a href="blog.html">BLOG</a></li>
                    <li><a href="contact.html">CONTACT</a></li>
                </ul>
                <!-- End Menu-->
                <!-- coopring-->
                <div class="row coopring">
                    <div class="col-md-8">
                        <p>&copy; 2015 Roken . All Rights Reserved.  1995 - 2015</p>
                    </div>
                </div>
                <!-- End coopring-->
            </div>
            <!-- End Nav-->
            <!-- Social-->
            <div class="col-md-4">
                <!-- Menu-->
                <ul class="social">
                    <li data-toggle="tooltip" title data-original-title="Facebook">
                        <a href="#" target="_blank"><i class="fa fa-facebook"></i></a>
                    </li>
                    <li data-toggle="tooltip" title data-original-title="Twitter">
                        <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
                    </li>
                    <li data-toggle="tooltip" title data-original-title="Youtube">
                        <a href="#" target="_blank"><i class="fa fa-youtube"></i></a>
                    </li>
                </ul>
                <!-- End Menu-->
            </div>
            <!-- End Social-->

        </div>

    </div>
</footer>

Blog.UI/Views/Shared/RightWidgetText.cshtml
@using Blog.Entity
@model PageSectionContent
<aside>
    <h4>@Model.Header</h4>
    <p>
        @Model.Content
    </p>
</aside>

Blog.UI/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Basic -->
    <meta charset="utf-8">
    <title>Roker  - Software, Technology , Corporate, Creative, Multi-Purpose, Responsive And Retina Html5/css3 Template</title>
    <meta name="keywords" content="HTML5 Template" />
    <meta name="description" content="Roker  - Corporate, Creative, Multi Purpose, Responsive And Retina Template">
    <meta name="author" content="iwthemes.com">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Theme CSS -->
    <link type="text/css" media="screen" rel="stylesheet" href="~/Content/UI/css/style.css" />
    <!-- Responsive CSS -->
    @*<link type="text/css" media="screen" rel="stylesheet" href="~/Content/UI/css/theme-responsive.css" />*@

    @* Varsayılan *@
    @*<link href="~/Content/UI/css/skins/blue/blue.css" rel="stylesheet" />*@

    @*<link href="~/Content/UI/css/skins/red/red.css" rel="stylesheet" />*@

    @Styles.Render("~/bundles/StyleCss")

    @Styles.Render("~/bundles/CssTheme")

    <!-- Skins Theme -->
    <link type="text/css" media="screen" rel="stylesheet" href="#" class="skin_color" />

    <!-- Head Libs -->
    <script src="~/Content/UI/js/modernizr.js"></script>

    <!-- Favicons -->
    <link rel="shortcut icon" href="~/Content/UI/img/icons/favicon.ico">
    <link rel="apple-touch-icon" href="~/Content/UI/img/icons/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="~/Content/UI/img/icons/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="~/Content/UI/img/icons/apple-touch-icon-114x114.png">

    <link href="~/Content/UI/css/icons/font-awesome.min.css" rel="stylesheet" />


    @*<img src="~/Content/UI/img/logo.png" />*@

    <!-- styles for IE -->
    <!--[if lte IE 8]>
        <link rel="stylesheet" href="~/Content/UI/css/ie/ie.css" type="text/css" media="screen" />
    <![endif]-->
    <!--[if lte IE 8]>
        <script src="~/Content/UI/js/responsive/html5shiv.js"></script>
        <script src="~/Content/UI/js/responsive/respond.js"></script>
    <![endif]-->
</head>
<body>

    <!--Preloader-->
    <div class="preloader">
        <div class="status">&nbsp;</div>
    </div>
    <!--End Preloader-->

    <!-- Theme-options -->
      @Html.Partial("ThemeOptionsPartial")
    <!-- End Theme-options -->

    <!-- layout-->
    <div id="layout" class="layout-wide">
        <!-- Login Client -->


        @Html.Partial("LoginClientPartial")

        @*<div class="jBar">
                <div class="container">


                </div>
            </div>*@
        <span class="jRibbon jTrigger up" title="Login"><i class="fa fa-plus"></i></span>
        <div class="line"></div>
        <!-- End Login Client -->
        <!-- Info Head -->
        @Html.Partial("InfoHeadPartial")
        <!-- Info Head -->
        <!-- Header-->
        @*@Html.Partial("HeadPartial")*@

        @*View Tarafında Bir Action Çağırma*@

        @Html.Action("HeadPartial", "Home")

        <!-- End Header-->
        <!-- Title Section -->
        @Html.Partial("TitleSectionPartial")
        <!-- End Title Section -->
        <!-- Works -->
        <section class="paddings">
            <div class="container">
                <div class="row">

                    <!-- Blog Post -->
                    @* Blog post ındex içerisine taşındı  *@

                    <div class="col-md-8">
                        @RenderBody()
                    </div>
                 
                    <!-- End Blog Post -->
                    <!-- Sidebars -->
                    <div class="col-md-4 sidebars">

                        @*<aside>
                            <h4>Searh Sidebar</h4>
                            <form class="search" action="#" method="Post">
                                <div class="input-group">
                                    <input class="form-control" placeholder="Search..." name="email" type="email" required="required">
                                    <span class="input-group-btn">
                                        <button class="btn btn-primary" type="submit" name="subscribe">Go!</button>
                                    </span>
                                </div>
                            </form>
                        </aside>*@

                        <hr>

                        <aside>
                           @Html.Action("RightCategoryPartial", "Home")
                        </aside>

                        @Html.Action("GetAllTags", "Tag")

                        @Html.Action("PopularAndRecentPartial", "CategoryDetail")


                        @Html.Action("RecentFlickrImages", "Home")

                        <hr>

                        @* Right Widget text *@

                        @Html.Action("GetRightWidget", "PageSection")

                    </div>
                    <!-- End Sidebars -->


                </div>
            </div>
            <!-- End Container-->
        </section>
        <!-- End Works-->
        <!-- footer top-->
        @Html.Partial("FooterTopPartial")
        <!-- End footer Top-->
        <!-- footer Center-->

        @Html.Partial("FooterCenter")
        <!-- End footer Center-->
        <!-- footer bottom-->
        @Html.Partial("FooterBottom")
        <!-- End footer bottom-->
    </div>
    <!-- End layout-->
    <!-- ======================= JQuery libs =========================== -->

    @Scripts.Render("~/bundles/js")

    @*
        <!-- jQuery local-->
        <script src="~/Content/UI/js/jquery.js"></script>

        <script type="text/javascript" src="~/Content/UI/js/jquery.js"></script>
        <!--Nav-->
        <script type="text/javascript" src="~/Content/UI/js/nav/tinynav.js"></script>
        <script type="text/javascript" src="~/Content/UI/js/nav/superfish.js"></script>
        <script type="text/javascript" src="~/Content/UI/js/nav/hoverIntent.js"></script>
        <script src="~/Content/UI/js/nav/jquery.sticky.js" type="text/javascript"></script>
        <!--Totop-->
        <script type="text/javascript" src="~/Content/UI/js/totop/jquery.ui.totop.js"></script>
        <!--Slide Revolution-->
        <script type="text/javascript" src="~/Content/UI/js/rs-plugin/js/jquery.themepunch.tools.min.js"></script>
        <script type='text/javascript' src='~/Content/UI/js/rs-plugin/js/jquery.themepunch.revolution.min.js'></script>
        <!--Ligbox-->
        <script type="text/javascript" src="~/Content/UI/js/fancybox/jquery.fancybox.js"></script>
        <!-- carousel.js-->
        <script src="~/Content/UI/js/carousel/carousel.js"></script>
        <!-- Twitter Feed-->
        <script src="~/Content/UI/js/twitter/jquery.tweet.js"></script>
        <!-- flickr Feed-->
        <script src="~/Content/UI/js/flickr/jflickrfeed.min.js"></script>
        <!--Scroll-->
        <script src="~/Content/UI/js/scrollbar/jquery.mCustomScrollbar.concat.min.js"></script>
        <!-- Maps -->
        <script src="~/Content/UI/js/maps/gmap3.js"></script>
        <!-- Filter -->
        <script src="~/Content/UI/js/filters/jquery.isotope.js" type="text/javascript"></script>
        <!-- Parallax-->
        <script type="text/javascript" src="~/Content/UI/js/parallax/jquery.inview.js"></script>
        <script type="text/javascript" src="~/Content/UI/js/parallax/nbw-parallax.js"></script>
        <!--Theme Options-->
        <script type="text/javascript" src="~/Content/UI/js/theme-options/theme-options.js"></script>
        <script type="text/javascript" src="~/Content/UI/js/theme-options/jquery.cookies.js"></script>
        <!-- Bootstrap.js-->
        <script type="text/javascript" src="~/Content/UI/js/bootstrap/bootstrap.js"></script>
        <!--MAIN FUNCTIONS-->
        <script type="text/javascript" src="~/Content/UI/js/main.js"></script>
        <!-- ======================= End JQuery libs =========================== -->
    *@
</body>
        </html>